/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ticketing.system.client;

import java.security.Timestamp;

/**
 *
 * @author ferdi
 */
public class FormPanelAcara extends javax.swing.JPanel {

    /**
     * Creates new form FormPanelAcara
     */
    String nama, lokasi, deskripsi;
    Timestamp tgl;
    int kuota;
    double harga;
    
    
    public FormPanelAcara() {
        initComponents();
    }
    
    public FormPanelAcara(FormAcara _parent, String nama, int kuota, String lokasi, Timestamp tgl, double harga, String deskripsi) {
        initComponents();
        this.nama = nama;
        this.lokasi = lokasi;
        this.deskripsi = deskripsi;
        this.kuota = kuota;
        this.harga = harga;
        this.tgl = tgl;
        
        jLabelNamaAcara.setText(nama);
        jLabelTanggal.setText(tgl.toString());
        jLabelKuota.setText(String.valueOf(kuota));
        jLabelLokasi.setText(lokasi);
        jLabelDeskripsi.setText(deskripsi);
        jLabelHarga.setText(String.valueOf(harga));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBook = new javax.swing.JButton();
        jLabelNamaAcara = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelKuota = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelLokasi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTanggal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jLabelDepartureDate1 = new javax.swing.JLabel();
        jLabelDeskripsi = new javax.swing.JLabel();
        jButtonBook1 = new javax.swing.JButton();

        jButtonBook.setText("Book");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });

        jLabelNamaAcara.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabelNamaAcara.setText("NAMA ACARA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel1.setText("Quota :");

        jLabelKuota.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabelKuota.setText("kuota");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelKuota))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabelKuota)
                .addContainerGap())
        );

        jLabelLokasi.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabelLokasi.setText("lokasi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel2.setText("Location :");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelLokasi))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jLabelLokasi)
                .addContainerGap())
        );

        jLabelTanggal.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabelTanggal.setText("TANGGAL");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel9.setText("Price :");

        jLabelHarga.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabelHarga.setText("jLabel10");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHarga)
                .addGap(58, 58, 58))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelHarga))
                .addContainerGap())
        );

        jLabelDepartureDate1.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabelDepartureDate1.setText("Description :");

        jLabelDeskripsi.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabelDeskripsi.setText("deksripsi");

        jButtonBook1.setText("Book");
        jButtonBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBook1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelNamaAcara)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDepartureDate1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTanggal)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTanggal)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNamaAcara)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDepartureDate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed

        // TODO add your handling code here:
//        JFrameBookTicket frameBookTicket = new JFrameBookTicket((JFrameScheduleList)this.parent, this.flightNumber, this.departureDate, this.departureAirport, this.arrivalAirport, this.seatClass, this.airlineName, this.price, ((JFrameScheduleList)parent).adult, ((JFrameScheduleList)parent).children, ((JFrameScheduleList)parent).infant);
//        frameBookTicket.setVisible(true);
//        parent.setVisible(false);

    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBook1ActionPerformed

        // TODO add your handling code here:
//        JFrameBookTicket frameBookTicket = new JFrameBookTicket((JFrameScheduleList)this.parent, this.flightNumber, this.departureDate, this.departureAirport, this.arrivalAirport, this.seatClass, this.airlineName, this.price, ((JFrameScheduleList)parent).adult, ((JFrameScheduleList)parent).children, ((JFrameScheduleList)parent).infant);
//        frameBookTicket.setVisible(true);
//        parent.setVisible(false);

    }//GEN-LAST:event_jButtonBook1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBook;
    public javax.swing.JButton jButtonBook1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDepartureDate1;
    private javax.swing.JLabel jLabelDeskripsi;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelKuota;
    private javax.swing.JLabel jLabelLokasi;
    private javax.swing.JLabel jLabelNamaAcara;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
