/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ticketing.system.client;
    
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Luky
 */
public class FormAcara extends javax.swing.JPanel {

    /**
     * Creates new form FormAcara
     */
    public FormAcara() {
        initComponents();
    }
    public FormAcara(DashBoard p,int id) {
        this();
        parent = p;
        idUser = id;
        RefreshTable();
    }
    DashBoard parent;
    int idUser;
    Acara acaraPilih = new Acara();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAcara1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelHasil = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldTanggal = new javax.swing.JTextField();
        jTextFieldLokasi = new javax.swing.JTextField();
        jButtonReservasi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonDeskripsi = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAcara1.setBackground(new java.awt.Color(255, 255, 255));
        btnAcara1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnAcara1.setForeground(new java.awt.Color(102, 102, 102));
        btnAcara1.setText("Acara");

        jTabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Lokasi", "Tanggal Acara", "Harga (Rp)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelHasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelHasil);
        if (jTabelHasil.getColumnModel().getColumnCount() > 0) {
            jTabelHasil.getColumnModel().getColumn(0).setResizable(false);
            jTabelHasil.getColumnModel().getColumn(1).setResizable(false);
            jTabelHasil.getColumnModel().getColumn(2).setResizable(false);
            jTabelHasil.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Nama :");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Lokasi :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Tanggal Acara :");

        jTextFieldNama.setEditable(false);
        jTextFieldNama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jTextFieldTanggal.setEditable(false);
        jTextFieldTanggal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jTextFieldLokasi.setEditable(false);
        jTextFieldLokasi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextFieldLokasi.setSelectionColor(new java.awt.Color(0, 0, 0));

        jButtonReservasi.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonReservasi.setText("Reservasi");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Harga :");

        jTextFieldHarga.setEditable(false);
        jTextFieldHarga.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Rp");

        jButtonDeskripsi.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonDeskripsi.setText("Lihat Deskripsi");
        jButtonDeskripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeskripsiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(107, 107, 107)
                                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(37, 37, 37)
                                                .addComponent(jTextFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(119, 119, 119))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDeskripsi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAcara1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnAcara1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonReservasi)
                            .addComponent(jButtonDeskripsi)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelHasilMouseClicked
        JTable klik = (JTable) evt.getSource();
        int row = klik.getSelectedRow();
        
        jTextFieldNama.setText(klik.getValueAt(row, 0).toString());
        jTextFieldLokasi.setText(klik.getValueAt(row, 1).toString());
        jTextFieldTanggal.setText(klik.getValueAt(row, 2).toString());
        jTextFieldHarga.setText(klik.getValueAt(row, 3).toString());
        
        acaraPilih = getAcaraByNama(jTextFieldNama.getText());
    }//GEN-LAST:event_jTabelHasilMouseClicked

    private void jButtonDeskripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeskripsiMouseClicked
        FormDeskripsiAcara form = new FormDeskripsiAcara(this, acaraPilih);
        form.show();
    }//GEN-LAST:event_jButtonDeskripsiMouseClicked

    private void RefreshTable()
    {
        jTabelHasil.removeAll();
        DefaultTableModel model = (DefaultTableModel) jTabelHasil.getModel();
        model.setRowCount(0);
        Object[] rowData=new Object[4];
        java.util.List<ticketing.system.client.Acara> listAcara = getAcara();
        
        for ( ticketing.system.client.Acara obj : listAcara)
        {
            if (obj instanceof ticketing.system.client.Acara)
            {
                ticketing.system.client.Acara tampung = (ticketing.system.client.Acara)obj;
                rowData[0]=tampung.getNama();                
                rowData[1]=tampung.getLokasi();
                rowData[2]=tampung.getTanggalAcara();
                rowData[3]=tampung.getHarga();
                model.addRow(rowData);
            }
        }
        resizeColumnWidth(jTabelHasil);
    }
    
    public void resizeColumnWidth(JTable table) {
        table.getColumnModel().getColumn(0).setMaxWidth(125);
        table.getColumnModel().getColumn(1).setMaxWidth(125);
        table.getColumnModel().getColumn(2).setMaxWidth(125);
        table.getColumnModel().getColumn(3).setMaxWidth(125);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAcara1;
    private javax.swing.JButton jButtonDeskripsi;
    private javax.swing.JButton jButtonReservasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelHasil;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldLokasi;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldTanggal;
    // End of variables declaration//GEN-END:variables

    

    private static Acara getAcaraByNama(java.lang.String nama) {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.getAcaraByNama(nama);
    }

    private static java.util.List<ticketing.system.client.Acara> getAcara() {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.getAcara();
    }

}
