/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ticketing.system.client;

/**
 *
 * @author Luky
 */
public class FormAcara extends javax.swing.JPanel {

    /**
     * Creates new form FormAcara
     */
    public FormAcara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcara = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAcara1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        btnAcara.setBackground(new java.awt.Color(255, 255, 255));
        btnAcara.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAcara.setForeground(new java.awt.Color(102, 102, 102));
        btnAcara.setText("Acara");
        btnAcara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcaraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcaraMouseExited(evt);
            }
        });

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAcara1.setBackground(new java.awt.Color(255, 255, 255));
        btnAcara1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnAcara1.setForeground(new java.awt.Color(102, 102, 102));
        btnAcara1.setText("Acara");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAcara1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnAcara1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcaraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcaraMouseEntered
        
    }//GEN-LAST:event_btnAcaraMouseEntered

    private void btnAcaraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcaraMouseExited
        
    }//GEN-LAST:event_btnAcaraMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAcara;
    private javax.swing.JLabel btnAcara1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
